import enLang from "../../../lngProvider/locales/en_US";
import {
  LAYOUT_TYPE,
  LAYOUT_TYPE_FULL,
  NAV_STYLE,
  NAV_STYLE_FIXED,
  THEME_COLOR_SELECTION,
  THEME_COLOR_SELECTION_PRESET,
  THEME_TYPE,
  THEME_TYPE_SEMI_DARK,

} from "../../../constants/ThemeSetting";
import { convertToLang } from '../../../routes/utils/commonUtils';

import {
  DEVICE_ID,
  USER_ID,
  DEVICE_REMAINING_DAYS,
  DEVICE_FLAGGED,
  DEVICE_STATUS,
  DEVICE_MODE,
  DEVICE_NAME,
  DEVICE_ACTIVATION_CODE,
  DEVICE_ACCOUNT_EMAIL,
  DEVICE_PGP_EMAIL,
  DEVICE_CHAT_ID,
  DEVICE_CLIENT_ID,
  DEVICE_DEALER_ID,
  DEVICE_DEALER_PIN,
  DEVICE_MAC_ADDRESS,
  DEVICE_SIM_ID,
  DEVICE_IMEI_1,
  DEVICE_SIM_1,
  DEVICE_IMEI_2,
  DEVICE_SIM_2,
  DEVICE_SERIAL_NUMBER,
  DEVICE_MODEL,
  DEVICE_START_DATE,
  DEVICE_EXPIRY_DATE,
  DEVICE_DEALER_NAME,
  DEVICE_S_DEALER,
  DEVICE_S_DEALER_NAME,
} from '../../../constants/DeviceConstants';

import {
  DEALER_ID,
  DEALER_NAME,
  DEALER_EMAIL,
  DEALER_PIN,
  DEALER_DEVICES,
  DEALER_TOKENS,
  Parent_Dealer,
  Parent_Dealer_ID
} from '../../../constants/DealerConstants';

import {
	APK_SHOW_ON_DEVICE,
	APK,
	APK_APP_NAME,
	APK_APP_LOGO,
	APK_PERMISSION
} from '../../../constants/ApkConstants';

export var initialSettings = {
  navCollapsed: true,
  navStyle: NAV_STYLE_FIXED,
  layoutType: LAYOUT_TYPE_FULL,
  themeType: THEME_TYPE_SEMI_DARK,
  colorSelection: THEME_COLOR_SELECTION_PRESET,

  pathname: '',
  width: window.innerWidth,
  isDirectionRTL: false,
  languages: [],
  translation: enLang,
  isSwitched: 'abc',
  deviceOptions: [
    { "key": DEVICE_ID, "value": convertToLang(enLang[DEVICE_ID], DEVICE_ID) },
    { "key": USER_ID, "value": convertToLang(enLang[USER_ID], USER_ID) },
    { "key": DEVICE_REMAINING_DAYS, "value": convertToLang(enLang[DEVICE_REMAINING_DAYS], DEVICE_REMAINING_DAYS) },
    { "key": DEVICE_STATUS, "value": convertToLang(enLang[DEVICE_STATUS], DEVICE_STATUS) },
    { "key": DEVICE_MODE, "value": convertToLang(enLang[DEVICE_MODE], DEVICE_MODE) },
    { "key": DEVICE_FLAGGED, "value": convertToLang(enLang[DEVICE_FLAGGED], DEVICE_FLAGGED) },
    { "key": DEVICE_NAME, "value": convertToLang(enLang[DEVICE_NAME], DEVICE_NAME) },
    { "key": DEVICE_ACCOUNT_EMAIL, "value": convertToLang(enLang[DEVICE_ACCOUNT_EMAIL], DEVICE_ACCOUNT_EMAIL) },
    { "key": DEVICE_CLIENT_ID, "value": convertToLang(enLang[DEVICE_CLIENT_ID], DEVICE_CLIENT_ID) },
    { "key": DEVICE_ACTIVATION_CODE, "value": convertToLang(enLang[DEVICE_ACTIVATION_CODE], DEVICE_ACTIVATION_CODE) },
    { "key": DEVICE_PGP_EMAIL, "value": convertToLang(enLang[DEVICE_PGP_EMAIL], DEVICE_PGP_EMAIL) },
    { "key": DEVICE_SIM_ID, "value": convertToLang(enLang[DEVICE_SIM_ID], DEVICE_SIM_ID) },
    { "key": DEVICE_CHAT_ID, "value": convertToLang(enLang[DEVICE_CHAT_ID], DEVICE_CHAT_ID) },
    { "key": DEVICE_DEALER_ID, "value": convertToLang(enLang[DEVICE_DEALER_ID], DEVICE_DEALER_ID) },
    { "key": DEVICE_DEALER_NAME, "value": convertToLang(enLang[DEVICE_DEALER_NAME], DEVICE_DEALER_NAME) },
    { "key": DEVICE_DEALER_PIN, "value": convertToLang(enLang[DEVICE_DEALER_PIN], DEVICE_DEALER_PIN) },
    { "key": DEVICE_MAC_ADDRESS, "value": convertToLang(enLang[DEVICE_MAC_ADDRESS], DEVICE_MAC_ADDRESS) },
    { "key": DEVICE_IMEI_1, "value": convertToLang(enLang[DEVICE_IMEI_1], DEVICE_IMEI_1) },
    { "key": DEVICE_SIM_1, "value": convertToLang(enLang[DEVICE_SIM_1], DEVICE_SIM_1) },
    { "key": DEVICE_IMEI_2, "value": convertToLang(enLang[DEVICE_IMEI_2], DEVICE_IMEI_2) },
    { "key": DEVICE_SIM_2, "value": convertToLang(enLang[DEVICE_SIM_2], DEVICE_SIM_2) },
    { "key": DEVICE_SERIAL_NUMBER, "value": convertToLang(enLang[DEVICE_SERIAL_NUMBER], DEVICE_SERIAL_NUMBER) },
    { "key": DEVICE_MODEL, "value": convertToLang(enLang[DEVICE_MODEL], DEVICE_MODEL) },
    { "key": DEVICE_S_DEALER, "value": convertToLang(enLang[DEVICE_S_DEALER], DEVICE_S_DEALER) },
    { "key": DEVICE_S_DEALER_NAME, "value": convertToLang(enLang[DEVICE_S_DEALER_NAME], DEVICE_S_DEALER_NAME) },
    { "key": DEVICE_START_DATE, "value": convertToLang(enLang[DEVICE_START_DATE], DEVICE_START_DATE) },
    { "key": DEVICE_EXPIRY_DATE, "value": convertToLang(enLang[DEVICE_EXPIRY_DATE], DEVICE_EXPIRY_DATE) },
  ],
  dealerOptions: [
    { "key": DEALER_ID, "value": convertToLang(enLang[DEALER_ID], DEALER_ID) },
    { "key": DEALER_NAME, "value": convertToLang(enLang[DEALER_NAME], DEALER_NAME) },
    { "key": DEALER_EMAIL, "value": convertToLang(enLang[DEALER_EMAIL], DEALER_EMAIL) },
    { "key": DEALER_PIN, "value": convertToLang(enLang[DEALER_PIN], DEALER_PIN) },
    { "key": DEALER_DEVICES, "value": convertToLang(enLang[DEALER_DEVICES], DEALER_DEVICES) },
    { "key": DEALER_TOKENS, "value": convertToLang(enLang[DEALER_TOKENS], DEALER_TOKENS) },
    { "key": Parent_Dealer, "value": convertToLang(enLang[Parent_Dealer], Parent_Dealer) },
    { "key": Parent_Dealer_ID, "value": convertToLang(enLang[Parent_Dealer_ID], Parent_Dealer_ID) },
  ],
  APKOptions: [
    { "key": APK_PERMISSION, "value": convertToLang(enLang[APK_PERMISSION], APK_PERMISSION)},
    { "key": APK_SHOW_ON_DEVICE, "value": convertToLang(enLang[APK_SHOW_ON_DEVICE], APK_SHOW_ON_DEVICE)},
    { "key": APK, "value": convertToLang(enLang[APK], APK)},
    { "key": APK_APP_NAME, "value": convertToLang(enLang[APK_APP_NAME], APK_APP_NAME)},
    { "key": APK_APP_LOGO, "value": convertToLang(enLang[APK_APP_LOGO], APK_APP_LOGO)},
  ],
  //  locale: {
  //   languageId: 'english',
  //   locale: 'en',
  //   name: 'English',
  //   icon: 'us',
  // },
};
