// Customize const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';
export const GET_LANGUAGE = 'GET_LANGUAGE';
export const LANGUAGES = 'LANGUAGES';

// AppFilter
export const GET_DROPDOWN = 'GET_DROPDOWN';
export const POST_DROPDOWN = 'POST_DROPDOWN';
export const POST_PAGINATION = 'POST_PAGINATION';
export const GET_PAGINATION = 'GET_PAGINATION'

//Contact Module const
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';

//Auth const
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const INVALID_TOKEN = 'INVALID_TOKEN';
export const COMPONENT_ALLOWED = 'COMPONENT_ALLOWED';
export const INVALID_RESPONSE = 'INVALID_RESPONSE';
export const ACCESS_DENIED = 'ACCESS_DENIED';
export const GET_USER = 'GET_USER';
export const BEFORE_COMPONENT_ALLOWED = 'BEFORE_COMPONENT_ALLOWED';
export const DUPLICATE_SIM_IDS = 'DUPLICATE_SIM_IDS';
export const NEW_DATA_INSERTED = 'NEW_DATA_INSERTED';
export const TWO_FACTOR_AUTH = 'TWO_FACTOR_AUTH';
export const VERIFY_CODE = 'VERIFY_CODE';
export const CODE_VERIFIED = 'CODE_VERIFIED';
export const GOTO_LOGIN = 'GOTO_LOGIN';
export const LOGIN_HISTORY = 'LOGIN_HISTORY';

//Device const
export const DEVICES_LIST = 'DEVICES_LIST';
export const SUSPEND_DEVICE = 'SUSPEND_DEVICE';
export const ACTIVATE_DEVICE = 'ACTIVATE_DEVICE';
export const CONNECT_DEVICE = "CONNECT_DEVICE";
export const EDIT_DEVICE = 'EDIT_DEVICE';
export const TRANSFER_DEVICE = 'TRANSFER_DEVICE';
export const TRANSFER_USER = 'TRANSFER_USER';
export const MESSAGE_HANDLER = 'MESSAGE_HANDLER';
export const TRANSFER_HISTORY = 'TRANSFER_HISTORY';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const ADD_DEVICE = 'ADD_DEVICE';
export const REJECT_DEVICE = 'REJECT_DEVICE';
export const NEW_DEVICES_LIST = 'NEW_DEVICES_LIST';
export const PRE_ACTIVATE_DEVICE = 'PRE_ACTIVATE_DEVICE';
export const SPIN_lOADING = 'SPIN_lOADING';
export const DELETE_UNLINK_DEVICE = 'DELETE_UNLINK_DEVICE';

export const NEW_REQUEST_LIST = 'NEW_REQUEST_LIST';
export const USER_CREDITS = 'USER_CREDITS';
export const REJECT_REQUEST = 'REJECT_REQUEST'
export const ACCEPT_REQUEST = 'ACCEPT_REQUEST'

//Dealer const
export const DEALERS_LIST = 'DEALERS_LIST';
export const SUSPEND_DEALERS = 'SUSPEND_DEALERS';
export const EDIT_DEALER = 'EDIT_DEALER';
export const DELETE_DEALERS = 'DELETE_DEALERS';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const ACTIVATE_DEALER = 'ACTIVATE_DEALER';
export const UNDO_DEALER = 'UNDO_DEALER';
export const ADD_DEALER = 'ADD_DEALER';
export const DEALERS_LIST_IN_SDEALER = 'DEALERS_LIST_IN_SDEALER';

// Apk const
export const APK_LIST = 'APK_LIST';
export const UNLINK_APK = 'UNLINK_APK';
export const ADD_APK = 'ADD_APK';
export const EDIT_APK = 'EDIT_APK';
export const APK_STATUS_CHANGED = 'APK_STATUS_CHANGED';
export const PERMISSION_SAVED = 'PERMISSION_SAVED';
export const RESET_UPLOAD_FORM = 'RESET_UPLOAD_FORM';
export const RESET_AUTH_UPDATE = 'RESET_AUTH_UPDATE';
export const CHECK_APK_NAME = 'CHECK_APK_NAME';
export const AUTHENTICATE_UPDATE_USER = 'AUTHENTICATE_UPDATE_USER';


// Connect Device 
export const RESET_DEVICE = 'RESET_DEVICE';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const GET_DEVICE_DETAILS = 'GET_DEVICE_DETAILS';
export const CLEAR_APPLICATIONS = 'CLEAR_APPLICATIONS';
export const CLEAR_STATE = 'CLEAR_STATE';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const GET_DEVICE_APPS = 'GET_DEVICE_APPS';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_DEVICE_HISTORIES = 'GET_DEVICE_HISTORIES';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const GET_APPS_PERMISSIONS = 'GET_APPS_PERMISSIONS';
export const DEVICE_SYNCED = 'device_synced';
export const SUBMIT_PASSWORD = 'SUBMIT_PASSWORD';
export const GUEST_PASSWORD = 'guest_password';
export const ENCRYPTED_PASSWORD = 'encrypted_password';
export const DURESS_PASSWORD = 'duress_password';
export const ADMIN_PASSWORD = 'admin_password';
export const ACTIVATE_DEVICE2 = 'ACTIVATE_DEVICE2';
export const SUSPEND_DEVICE2 = 'SUSPEND_DEVICE2';
export const GET_USER_ACC_ID = 'GET_USER_ACC_ID';
export const FLAG_DEVICE = 'FLAG_DEVICE';
export const UNFLAG_DEVICE = 'UNFLAG_DEVICE';
export const WIPE_DEVICE = 'WIPE_DEVICE';
export const CHECKPASS = 'CHECKPASS';
export const CHECK_BACKUP_PASS = 'CHECK_BACKUP_PASS';
export const GET_DEALER_APPS = 'GET_DEALER_APPS';
export const HANDLE_CHECK_EXTENSION = 'HANDLE_CHECK_EXTENSION';
export const HANDLE_CHECK_ALL_EXTENSION = 'HANDLE_CHECK_ALL_EXTENSION';
export const HANDLE_CHECK_APP_POLICY = 'HANDLE_CHECK_APP_POLICY';
export const HANDLE_CHECK_SYSTEM_PERMISSIONS = 'HANDLE_CHECK_SYSTEM_PERMISSIONS';
export const HANDLE_CHECK_ALL_APP_POLICY = 'HANDLE_CHECK_ALL_APP_POLICY';
export const HANDLE_APPS_GOTTED = 'HANDLE_APPS_GOTTED';

export const SHOW_PUSH_APPS_MODAL = 'SHOW_PUSH_APPS_MODAL';
export const UNDO_EXTENSIONS = 'UNDO_EXTENSIONS';
export const REDO_EXTENSIONS = 'REDO_EXTENSIONS';
export const HANDLE_CHECK_CONTROL = 'HANDLE_CHECK_CONTROL';
export const HANDLE_CHECK_MAIN_SETTINGS = 'HANDLE_CHECK_MAIN_SETTINGS';
export const HANDLE_CHECK_SECURE_SETTINGS = 'HANDLE_CHECK_SECURE_SETTINGS';

export const UNDO_CONTROLS = 'UNDO_CONTROLS';
export const REDO_CONTROLS = 'REDO_CONTROLS';

export const PUSH_APP_CHECKED = 'PUSH_APP_CHECKED';
export const RESET_PUSH_APPS = 'RESET_PUSH_APPS';
export const HANDLE_CHECK_ALL_PUSH_APPS = 'HANDLE_CHECK_ALL_PUSH_APPS';

export const CHANGE_PAGE = 'CHANGE_PAGE';

export const HANDLE_CHECK_APP = 'HANDLE_CHECK_APP';
export const HANDLE_CHECK_ALL = 'HANDLE_CHECK_ALL';
export const CHECK_HANDLE_ALL_POLICY = 'CHECK_HANDLE_ALL_POLICY';

export const PUSH_APPS = 'PUSH_APPS';
export const PULL_APPS = 'PULL_APPS';
export const UNDO_APPS = "UNDO_APPS";
export const REDO_APPS = 'REDO_APPS';
export const SHOW_PULL_APPS_MODAL = 'SHOW_PULL_APPS_MODAL';

export const SAVE_POLICY = 'SAVE_POLICY';
export const APPLY_POLICY = 'APPLY_POLICY';
export const POLICY_PERMISSION_SAVED = 'POLICY_PERMISSION_SAVED';
export const GET_SYSTEM_PERMISSIONS = 'GET_SYSTEM_PERMISSIONS';

export const APPLY_SETTINGS = 'APPLY_SETTINGS';

export const SETTINGS_APPLIED = 'SETTINGS_APPLIED';
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
// export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const LOAD_PROFILE = 'LOAD_PROFILE';
export const SHOW_HISTORY_MODAL = 'SHOW_HISTORY_MODAL';
export const SHOW_SAVE_PROFILE_MODAL = 'SHOW_SAVE_PROFILE_MODAL';
export const HANDLE_PROFILE_INPUT = 'HANDLE_PROFILE_INPUT';
export const POLICY = 'policy';
export const PROFILE = 'profile';
export const SAVE_PROFILE = 'SAVE_PROFILE';
export const UNLINK_DEVICE = 'UNLINK_DEVICE';
export const HANDLE_POLICY_STATUS = 'HANDLE_POLICY_STATUS';
export const EDIT_POLICY = 'EDIT_POLICY';
export const SAVE_POLICY_CHANGES = 'SAVE_POLICY_CHANGES';
export const HIDE_POLICY_CONFIRM = 'HIDE_POLICY_CONFIRM';

export const LOADING = 'LOADING';
export const IMPORT_CSV = 'IMPORT_CSV';
export const GET_SIM_IDS = 'GET_SIM_IDS';
export const GET_CHAT_IDS = 'GET_CHAT_IDS';
export const GET_PGP_EMAILS = 'GET_PGP_EMAILS';
export const GET_USED_PGP_EMAILS = 'GET_USED_PGP_EMAILS';
export const GET_USED_CHAT_IDS = 'GET_USED_CHAT_IDS';
export const GET_USED_SIM_IDS = 'GET_USED_SIM_IDS';
export const RELEASE_CSV = 'RELEASE_CSV';
export const GET_IMIE_HISTORY = 'GET_IMIE_HISTORY';
export const WRITE_IMEI = 'WRITE_IMEI';
export const CREATE_BACKUP_DB = 'CREATE_BACKUP_DB';



// Policy consts
export const GET_POLICIES = 'GET_POLICIES'
export const DEFAULT_POLICY_CHANGE = 'DEFAULT_POLICY_CHANGE';
export const ADD_APPS_TO_POLICIES = 'ADD_APPS_TO_POLICIES';
export const REMOVE_APPS_FROM_POLICIES = 'REMOVE_APPS_FROM_POLICIES';
export const CHECK_TOGGLE_BUTTONS = 'CHECK_TOGGLE_BUTTONS';
export const RESET_POLICY = 'RESET_POLICY';
export const RESET_ADD_POLICY_FORM = 'RESET_ADD_POLICY_FORM';


// Users consts
export const SAVE_USERS = 'SAVE_USERS'
export const EDIT_USERS = 'EDIT_USERS'
export const LOAD_USER = 'LOAD_USER'
export const USERS_LIST = 'USERS_LIST'
export const DELETE_USER = 'DELETE_USER'
export const UNDO_DELETE_USER = 'UNDO_DELETE_USER'

//App Market Constants
export const TRANSFER_APPS = 'TRANSFER_APPS'
export const GET_MARKET_APPS = 'GET_MARKET_APPS'
export const UNINSTALL_PERMISSION_CHANGED = 'UNINSTALL_PERMISSION_CHANGED'


// Socket Actions
export const FINISHED_PUSH_APPS = 'FINISHED_PUSH_APPS';
export const FINISHED_PULL_APPS = 'FINISHED_PULL_APPS';
export const FINISHED_POLICY = 'FINISHED_POLICY';
export const FINISHED_WIPE = 'FINISHED_WIPE';
export const FINISHED_POLICY_STEP = 'FINISHED_POLICY_STEP';
export const FINISHED_IMEI = 'FINISHED_IMEI';
export const IN_PROCESS = 'IN_PROCESS';
export const SINGLE_APP_PUSHED = 'SINGLE_APP_PUSHED';
export const SINGLE_APP_PULLED = 'SINGLE_APP_PULLED';
export const GET_APP_JOBS = 'GET_APP_JOBS';


export const SHOW_BACKUP_MODAL = 'SHOW_BACKUP_MODAL';

export const SAVE_ID_PRICES = 'SAVE_ID_PRICES';
export const SAVE_PACKAGE = 'SAVE_PACKAGE';
export const GET_PACKAGES = 'GET_PACKAGES';
export const GET_PARENT_PACKAGES = 'GET_PARENT_PACKAGES';
export const PURCHASE_CREDITS = 'PURCHASE_CREDITS';
export const GET_PRICES = 'GET_PRICES';
export const SET_PRICE = 'SET_PRICE';
export const RESET_PRICE = 'RESET_PRICE';
export const RESYNC_IDS = 'RESYNC_IDS';



// Sim Module (connect device)
export const ADD_SIM_REGISTER = "ADD_SIM_REGISTER";
export const GET_SIMS = "GET_SIMS";
export const UPDATE_SIM = "UPDATE_SIM";
export const DELETE_SIM = "DELETE_SIM";
export const SIM_HISTORY = "SIM_HISTORY";
export const GET_UNREG_SIMS = "GET_UNREG_SIMS";


export const RECEIVE_SIM_DATA = "RECEIVE_SIM_DATA";


// Agent constants (Dealer Agents)
export const AGENT_LIST = 'AGENT_LIST';
export const SAVE_AGENT = 'SAVE_AGENT';
export const DELETE_AGENT = 'DELETE_AGENT';
export const EDIT_AGENT = 'EDIT_AGENT';
export const UPDATE_AGENT = 'UPDATE_AGENT';
export const CHANGE_AGENT_STATUS = 'CHANGE_AGENT_STATUS';
export const RESET_AGENT_PWD = 'RESET_AGENT_PWD'



// Dashboard constants 

export const GET_DASHBOARD_DATA = 'GET_DASHBOARD_DATA';