import React, { Component, Fragment } from 'react'
import IntlMessages from "../util/IntlMessages";

export const DEVICE_ID = <IntlMessages id="tableHeadings.DEVICEID" />;
export const USER_ID = <IntlMessages id="tableHeadings.USERID" />;
export const DEVICE_REMAINING_DAYS =  <IntlMessages id="tableHeadings.REMAININGDAYS" />;
export const DEVICE_FLAGGED =  <IntlMessages id="tableHeadings.FLAGGED" />;
export const DEVICE_STATUS = <IntlMessages id="tableHeadings.STATUS" />;
export const DEVICE_MODE = <IntlMessages id="tableHeadings.MODE" />;
export const DEVICE_NAME = <IntlMessages id="tableHeadings.DEVICENAME" />;
export const DEVICE_ACTIVATION_CODE =  <IntlMessages id="tableHeadings.ACTIVATIONCODE" />;
export const DEVICE_ACCOUNT_EMAIL =  <IntlMessages id="tableHeadings.ACCOUNTEMAIL" />;
export const DEVICE_PGP_EMAIL = <IntlMessages id="tableHeadings.PGPEMAIL" />;
export const DEVICE_CHAT_ID = <IntlMessages id="tableHeadings.CHATID" />;
export const DEVICE_CLIENT_ID = <IntlMessages id="tableHeadings.CLIENTID" />;
export const DEVICE_DEALER_ID = <IntlMessages id="tableHeadings.DEALERID" />;
export const DEVICE_DEALER_PIN = <IntlMessages id="tableHeadings.DEALERPIN" />;
export const DEVICE_MAC_ADDRESS = <IntlMessages id="tableHeadings.MACADDRESS" />;
export const DEVICE_SIM_ID = <IntlMessages id="tableHeadings.SIMID" />;
export const DEVICE_IMEI_1 = <IntlMessages id="tableHeadings.IMEI1" />;
export const DEVICE_SIM_1 = <IntlMessages id="tableHeadings.SIM1" />;
export const DEVICE_IMEI_2 = <IntlMessages id="tableHeadings.IMEI2" />;
export const DEVICE_SIM_2 = <IntlMessages id="tableHeadings.SIM2" />;
export const DEVICE_SERIAL_NUMBER = <IntlMessages id="tableHeadings.SERIALNUMBER" />;
export const DEVICE_MODEL = <IntlMessages id="tableHeadings.MODEL" />;
export const DEVICE_DEALER_NAME = <IntlMessages id="tableHeadings.DEALERNAME" />;
export const DEVICE_S_DEALER = <IntlMessages id="tableHeadings.S-DEALER" />;
export const DEVICE_S_DEALER_NAME = <IntlMessages id="tableHeadings.S-DEALERNAME" />;
export const IP_ADDRESS = <IntlMessages id="tableHeadings.IPAddress" />;
export const DEVICE_START_DATE = <IntlMessages id="tableHeadings.STARTDATE" />;
export const DEVICE_EXPIRY_DATE = <IntlMessages id="tableHeadings.EXPIRYDATE" />;