export const DEVICE_ID = "tableHeadings.DEVICEID";
export const DEVICE_EDIT = "tableHeadings.DEVICEedit";
export const USER_ID = "tableHeadings.USERID";
export const DEVICE_REMAINING_DAYS =  "tableHeadings.REMAININGDAYS";
export const DEVICE_FLAGGED =  "tableHeadings.FLAGGED";
export const DEVICE_STATUS = "tableHeadings.STATUS";
export const DEVICE_MODE = "tableHeadings.MODE";
export const DEVICE_NAME = "tableHeadings.DEVICENAME";
export const DEVICE_ACTIVATION_CODE =  "tableHeadings.ACTIVATIONCODE";
export const DEVICE_ACCOUNT_EMAIL =  "tableHeadings.ACCOUNTEMAIL";
export const DEVICE_PGP_EMAIL = "tableHeadings.PGPEMAIL";
export const DEVICE_CHAT_ID = "tableHeadings.CHATID";
export const DEVICE_CLIENT_ID = "tableHeadings.CLIENTID";
export const DEVICE_DEALER_ID = "tableHeadings.DEALERID";
export const DEVICE_DEALER_PIN = "tableHeadings.DEALERPIN";
export const DEVICE_MAC_ADDRESS = "tableHeadings.MACADDRESS";
export const DEVICE_SIM_ID = "tableHeadings.SIMID";
export const DEVICE_IMEI_1 = "tableHeadings.IMEI1";
export const DEVICE_SIM_1 = "tableHeadings.SIM1";
export const DEVICE_IMEI_2 = "tableHeadings.IMEI2";
export const DEVICE_SIM_2 = "tableHeadings.SIM2";
export const DEVICE_SERIAL_NUMBER = "tableHeadings.SERIALNUMBER";
export const DEVICE_MODEL = "tableHeadings.MODEL";
export const DEVICE_DEALER_NAME = "tableHeadings.DEALERNAME";
export const DEVICE_S_DEALER = "tableHeadings.S-DEALER";
export const DEVICE_S_DEALER_NAME = "tableHeadings.S-DEALERNAME";
export const IP_ADDRESS = "tableHeadings.IPAddress";
export const DEVICE_START_DATE = "tableHeadings.STARTDATE";
export const DEVICE_EXPIRY_DATE = "tableHeadings.EXPIRYDATE";

export const Required_Fields = "required.fields.id"; // Required Fields
export const DEVICE_Select_SIM_ID = "tableHeadings.Select.SIMID"; // "Select Sim ID"
export const DEVICE_Select_CHAT_ID = "tableHeadings.Select.CHATID"; // Select Chat ID
export const Device_Note = "device.note.id"; //Note
export const Device_Valid_For = "device.valid.for.id"; // VALID FOR(DAYS)
export const Device_Valid_days_Required = "device.valid.days.required.id";  // Valid days required
